version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: on-failure  #no  always  on-failure  unless-stopped
    command: redis-server --appendonly yes --bind 0.0.0.0

  mysql:
    image: mysql:5.6
    volumes:
      - "./db/mysql_data:/var/lib/mysql"
      - "./db/mysql_init:/docker-entrypoint-initdb.d/"
    restart: on-failure
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_gmicro
      MYSQL_USER: liangjf
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

  jaeger:
    image: jaegertracing/all-in-one:1.7
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  #web api
  web_comment:
    build:
      context: ./bin/web/web_comment
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
      CONFIGOR_MYSQL_ADDR: mysql-server:3306
    links:
      - jaeger
    ports:
      - "7010:7010"
    restart: on-failure
    depends_on:
      - srv_comment
      - srv_identify
      - srv_post
      - srv_user

  web_post:
    build:
      context: ./bin/web/web_post
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
      CONFIGOR_MYSQL_ADDR: mysql-server:3306
    links:
      - jaeger
    ports:
      - "7030:7030"
    restart: on-failure
    depends_on:
      - srv_comment
      - srv_identify
      - srv_post
      - srv_user

  web_user:
    build:
      context: ./bin/web/web_user
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
      CONFIGOR_MYSQL_ADDR: mysql-server:3306
    links:
      - jaeger
    ports:
      - "7020:7020"
    restart: on-failure
    depends_on:
      - srv_comment
      - srv_identify
      - srv_post
      - srv_user

  #服务
  srv_comment:
    build:
      context: ./bin/srv/srv_comment
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
      CONFIGOR_MYSQL_ADDR: mysql-server:3306
    restart: on-failure
    links:
      - mysql:mysql-server
      - redis:redis-server
      - jaeger
    depends_on:
      - mysql
      - redis
      - jaeger

  srv_identify:
    build:
      context: ./bin/srv/srv_identify
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
    restart: on-failure
    links:
      - mysql:mysql-server
      - redis:redis-server
      - jaeger
    depends_on:
      - mysql
      - redis
      - jaeger

  srv_post:
    build:
      context: ./bin/srv/srv_post
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
    restart: on-failure
    links:
      - mysql:mysql-server
      - redis:redis-server
      - jaeger
    depends_on:
      - mysql
      - redis
      - jaeger

  srv_user:
    build:
      context: ./bin/srv/srv_user
      dockerfile: Dockerfile
    environment:
      CONFIGOR_TRACE_ADDRESS: jaeger:6831
      CONFIGOR_MYSQL_ADDR: mysql-server:3306
    restart: on-failure
    links:
      - mysql:mysql-server
      - redis:redis-server
      - jaeger:jaeger-server
    depends_on:
      - mysql
      - redis
      - jaeger




