language:
  - go

sudo: true

go:
  - "1.13.x"

env:
  - GO111MODULE=on

before_install:
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/dockerfile.sh

script:
  - ./scripts/build.sh
  - ./scripts/dockerfile.sh
  - cd deployments && sudo docker-compose up