// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api.proto

package gmicro_srv_identify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for IdentifySrv service

type IdentifySrvService interface {
	AuthMid(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthResponse, error)
}

type identifySrvService struct {
	c    client.Client
	name string
}

func NewIdentifySrvService(name string, c client.Client) IdentifySrvService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "gmicro.srv.identify"
	}
	return &identifySrvService{
		c:    c,
		name: name,
	}
}

func (c *identifySrvService) AuthMid(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "IdentifySrv.AuthMid", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IdentifySrv service

type IdentifySrvHandler interface {
	AuthMid(context.Context, *AuthRequest, *AuthResponse) error
}

func RegisterIdentifySrvHandler(s server.Server, hdlr IdentifySrvHandler, opts ...server.HandlerOption) error {
	type identifySrv interface {
		AuthMid(ctx context.Context, in *AuthRequest, out *AuthResponse) error
	}
	type IdentifySrv struct {
		identifySrv
	}
	h := &identifySrvHandler{hdlr}
	return s.Handle(s.NewHandler(&IdentifySrv{h}, opts...))
}

type identifySrvHandler struct {
	IdentifySrvHandler
}

func (h *identifySrvHandler) AuthMid(ctx context.Context, in *AuthRequest, out *AuthResponse) error {
	return h.IdentifySrvHandler.AuthMid(ctx, in, out)
}
