// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package gmicro_srv_post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostArticleRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	IsOriginal           int32    `protobuf:"varint,5,opt,name=IsOriginal,proto3" json:"IsOriginal,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArticleRequest) Reset()         { *m = PostArticleRequest{} }
func (m *PostArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PostArticleRequest) ProtoMessage()    {}
func (*PostArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PostArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArticleRequest.Unmarshal(m, b)
}
func (m *PostArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArticleRequest.Marshal(b, m, deterministic)
}
func (m *PostArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArticleRequest.Merge(m, src)
}
func (m *PostArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PostArticleRequest.Size(m)
}
func (m *PostArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostArticleRequest proto.InternalMessageInfo

func (m *PostArticleRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PostArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostArticleRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PostArticleRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *PostArticleRequest) GetIsOriginal() int32 {
	if m != nil {
		return m.IsOriginal
	}
	return 0
}

func (m *PostArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PostArticleRespond struct {
	ArticleId            int32    `protobuf:"varint,1,opt,name=ArticleId,proto3" json:"ArticleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArticleRespond) Reset()         { *m = PostArticleRespond{} }
func (m *PostArticleRespond) String() string { return proto.CompactTextString(m) }
func (*PostArticleRespond) ProtoMessage()    {}
func (*PostArticleRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PostArticleRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArticleRespond.Unmarshal(m, b)
}
func (m *PostArticleRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArticleRespond.Marshal(b, m, deterministic)
}
func (m *PostArticleRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArticleRespond.Merge(m, src)
}
func (m *PostArticleRespond) XXX_Size() int {
	return xxx_messageInfo_PostArticleRespond.Size(m)
}
func (m *PostArticleRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArticleRespond.DiscardUnknown(m)
}

var xxx_messageInfo_PostArticleRespond proto.InternalMessageInfo

func (m *PostArticleRespond) GetArticleId() int32 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type GetArticleRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ArticleId            int32    `protobuf:"varint,2,opt,name=ArticleId,proto3" json:"ArticleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleRequest) Reset()         { *m = GetArticleRequest{} }
func (m *GetArticleRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleRequest) ProtoMessage()    {}
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *GetArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleRequest.Unmarshal(m, b)
}
func (m *GetArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleRequest.Merge(m, src)
}
func (m *GetArticleRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleRequest.Size(m)
}
func (m *GetArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleRequest proto.InternalMessageInfo

func (m *GetArticleRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetArticleRequest) GetArticleId() int32 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type GetArticleRespond struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	IsOriginal           int32    `protobuf:"varint,4,opt,name=IsOriginal,proto3" json:"IsOriginal,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	LastUpdateTime       string   `protobuf:"bytes,7,opt,name=LastUpdateTime,proto3" json:"LastUpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleRespond) Reset()         { *m = GetArticleRespond{} }
func (m *GetArticleRespond) String() string { return proto.CompactTextString(m) }
func (*GetArticleRespond) ProtoMessage()    {}
func (*GetArticleRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetArticleRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleRespond.Unmarshal(m, b)
}
func (m *GetArticleRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleRespond.Marshal(b, m, deterministic)
}
func (m *GetArticleRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleRespond.Merge(m, src)
}
func (m *GetArticleRespond) XXX_Size() int {
	return xxx_messageInfo_GetArticleRespond.Size(m)
}
func (m *GetArticleRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleRespond.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleRespond proto.InternalMessageInfo

func (m *GetArticleRespond) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetArticleRespond) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GetArticleRespond) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetArticleRespond) GetIsOriginal() int32 {
	if m != nil {
		return m.IsOriginal
	}
	return 0
}

func (m *GetArticleRespond) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GetArticleRespond) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *GetArticleRespond) GetLastUpdateTime() string {
	if m != nil {
		return m.LastUpdateTime
	}
	return ""
}

type DelArticleRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ArticleId            int32    `protobuf:"varint,2,opt,name=ArticleId,proto3" json:"ArticleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelArticleRequest) Reset()         { *m = DelArticleRequest{} }
func (m *DelArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DelArticleRequest) ProtoMessage()    {}
func (*DelArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *DelArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelArticleRequest.Unmarshal(m, b)
}
func (m *DelArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelArticleRequest.Marshal(b, m, deterministic)
}
func (m *DelArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelArticleRequest.Merge(m, src)
}
func (m *DelArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DelArticleRequest.Size(m)
}
func (m *DelArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelArticleRequest proto.InternalMessageInfo

func (m *DelArticleRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DelArticleRequest) GetArticleId() int32 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type DelArticleRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelArticleRespond) Reset()         { *m = DelArticleRespond{} }
func (m *DelArticleRespond) String() string { return proto.CompactTextString(m) }
func (*DelArticleRespond) ProtoMessage()    {}
func (*DelArticleRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *DelArticleRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelArticleRespond.Unmarshal(m, b)
}
func (m *DelArticleRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelArticleRespond.Marshal(b, m, deterministic)
}
func (m *DelArticleRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelArticleRespond.Merge(m, src)
}
func (m *DelArticleRespond) XXX_Size() int {
	return xxx_messageInfo_DelArticleRespond.Size(m)
}
func (m *DelArticleRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_DelArticleRespond.DiscardUnknown(m)
}

var xxx_messageInfo_DelArticleRespond proto.InternalMessageInfo

func (m *DelArticleRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*PostArticleRequest)(nil), "gmicro.srv.post.PostArticleRequest")
	proto.RegisterType((*PostArticleRespond)(nil), "gmicro.srv.post.PostArticleRespond")
	proto.RegisterType((*GetArticleRequest)(nil), "gmicro.srv.post.GetArticleRequest")
	proto.RegisterType((*GetArticleRespond)(nil), "gmicro.srv.post.GetArticleRespond")
	proto.RegisterType((*DelArticleRequest)(nil), "gmicro.srv.post.DelArticleRequest")
	proto.RegisterType((*DelArticleRespond)(nil), "gmicro.srv.post.DelArticleRespond")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x6d, 0xb7, 0x6e, 0xec, 0x08, 0x53, 0x0f, 0x22, 0x61, 0x88, 0x8c, 0x0a, 0xba, 0xab,
	0x5e, 0xcc, 0x27, 0x18, 0x15, 0x64, 0x20, 0x28, 0x75, 0x13, 0xbc, 0xac, 0x6b, 0x98, 0x81, 0xae,
	0xa9, 0x49, 0xb6, 0x97, 0xf1, 0xd6, 0x97, 0xf2, 0x6d, 0xa4, 0x69, 0xe6, 0xfa, 0x67, 0x74, 0x17,
	0xde, 0xf5, 0x7c, 0x7c, 0xe7, 0x4b, 0xf2, 0x3b, 0xa7, 0xd0, 0x0b, 0x53, 0xe6, 0xa5, 0x82, 0x2b,
	0x8e, 0x27, 0xcb, 0x15, 0x5b, 0x08, 0xee, 0x49, 0xb1, 0xf1, 0x52, 0x2e, 0x95, 0xfb, 0x6d, 0x01,
	0x3e, 0x73, 0xa9, 0x26, 0x42, 0xb1, 0x45, 0x4c, 0x03, 0xfa, 0xb9, 0xa6, 0x52, 0xe1, 0x29, 0xb4,
	0xe6, 0x2c, 0x22, 0xd6, 0xd0, 0x1a, 0xf5, 0x82, 0xec, 0x13, 0xcf, 0xc1, 0x99, 0x31, 0x15, 0x53,
	0x62, 0x6b, 0x2d, 0x2f, 0xb4, 0xca, 0x53, 0xb6, 0x20, 0x2d, 0xa3, 0x66, 0x05, 0x5e, 0x40, 0x67,
	0xb2, 0x56, 0x1f, 0x5c, 0x90, 0xb6, 0x96, 0x4d, 0x85, 0x57, 0x00, 0x53, 0xf9, 0x24, 0xd8, 0x92,
	0x25, 0x61, 0x4c, 0x9c, 0xa1, 0x35, 0x72, 0x82, 0x82, 0x82, 0x04, 0xba, 0x3e, 0x4f, 0x14, 0x4d,
	0x14, 0xe9, 0xe8, 0xc6, 0x6d, 0xe9, 0x8e, 0x2b, 0xb7, 0x94, 0x29, 0x4f, 0x22, 0xbc, 0x84, 0x9e,
	0x51, 0xa6, 0xf9, 0x5d, 0x9d, 0x60, 0x27, 0xb8, 0x3e, 0x9c, 0x3d, 0xd0, 0xc3, 0x0f, 0x2b, 0x85,
	0xd8, 0xd5, 0x90, 0x1f, 0xab, 0x9c, 0x92, 0x1f, 0xfc, 0x07, 0xc3, 0xda, 0x0b, 0xc3, 0xde, 0x0f,
	0xa3, 0xd5, 0x00, 0xa3, 0xdd, 0x04, 0xc3, 0x29, 0xc1, 0xc8, 0x3a, 0x7d, 0x41, 0x43, 0x45, 0x67,
	0x6c, 0x45, 0x0d, 0xa9, 0x82, 0x82, 0x37, 0xd0, 0x7f, 0x0c, 0xa5, 0x9a, 0xa7, 0xd1, 0xd6, 0xd3,
	0xd5, 0x9e, 0x8a, 0x9a, 0x01, 0xba, 0xa7, 0xf1, 0x3f, 0x01, 0xdd, 0x96, 0x43, 0x72, 0x3e, 0x08,
	0x6d, 0x9f, 0x47, 0xd4, 0xcc, 0x44, 0x7f, 0x8f, 0xbf, 0x6c, 0xe8, 0x17, 0x66, 0xf8, 0x22, 0x36,
	0xf8, 0x06, 0xc7, 0x05, 0x05, 0xaf, 0xbd, 0xca, 0x76, 0x7a, 0xf5, 0xcd, 0x1c, 0x1c, 0x30, 0xe9,
	0xf3, 0xdd, 0x23, 0x7c, 0x05, 0xd8, 0x8d, 0x0d, 0xdd, 0x5a, 0x53, 0x6d, 0x33, 0x06, 0xcd, 0x9e,
	0x42, 0xee, 0xee, 0xb9, 0x7b, 0x72, 0x6b, 0x40, 0x07, 0xcd, 0x1e, 0x93, 0xfb, 0xde, 0xd1, 0xff,
	0xe7, 0xdd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0xe9, 0xca, 0xd7, 0xac, 0x03, 0x00, 0x00,
}
