// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api.proto

package gmicro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterRespond, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginRespond, error)
	Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoRespond, error)
	CoinAdd(ctx context.Context, in *CoinAddRequest, opts ...client.CallOption) (*CoinAddResponse, error)
	CoinGet(ctx context.Context, in *CoinGetRequest, opts ...client.CallOption) (*CoinGetResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "gmicro.srv.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterRespond, error) {
	req := c.c.NewRequest(c.name, "User.Register", in)
	out := new(RegisterRespond)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginRespond, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(LoginRespond)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoRespond, error) {
	req := c.c.NewRequest(c.name, "User.Info", in)
	out := new(InfoRespond)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CoinAdd(ctx context.Context, in *CoinAddRequest, opts ...client.CallOption) (*CoinAddResponse, error) {
	req := c.c.NewRequest(c.name, "User.CoinAdd", in)
	out := new(CoinAddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CoinGet(ctx context.Context, in *CoinGetRequest, opts ...client.CallOption) (*CoinGetResponse, error) {
	req := c.c.NewRequest(c.name, "User.CoinGet", in)
	out := new(CoinGetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Register(context.Context, *RegisterRequest, *RegisterRespond) error
	Login(context.Context, *LoginRequest, *LoginRespond) error
	Info(context.Context, *InfoRequest, *InfoRespond) error
	CoinAdd(context.Context, *CoinAddRequest, *CoinAddResponse) error
	CoinGet(context.Context, *CoinGetRequest, *CoinGetResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Register(ctx context.Context, in *RegisterRequest, out *RegisterRespond) error
		Login(ctx context.Context, in *LoginRequest, out *LoginRespond) error
		Info(ctx context.Context, in *InfoRequest, out *InfoRespond) error
		CoinAdd(ctx context.Context, in *CoinAddRequest, out *CoinAddResponse) error
		CoinGet(ctx context.Context, in *CoinGetRequest, out *CoinGetResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Register(ctx context.Context, in *RegisterRequest, out *RegisterRespond) error {
	return h.UserHandler.Register(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *LoginRequest, out *LoginRespond) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *userHandler) Info(ctx context.Context, in *InfoRequest, out *InfoRespond) error {
	return h.UserHandler.Info(ctx, in, out)
}

func (h *userHandler) CoinAdd(ctx context.Context, in *CoinAddRequest, out *CoinAddResponse) error {
	return h.UserHandler.CoinAdd(ctx, in, out)
}

func (h *userHandler) CoinGet(ctx context.Context, in *CoinGetRequest, out *CoinGetResponse) error {
	return h.UserHandler.CoinGet(ctx, in, out)
}
