// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package gmicro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RegisterRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RegisterRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRespond) Reset()         { *m = RegisterRespond{} }
func (m *RegisterRespond) String() string { return proto.CompactTextString(m) }
func (*RegisterRespond) ProtoMessage()    {}
func (*RegisterRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *RegisterRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRespond.Unmarshal(m, b)
}
func (m *RegisterRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRespond.Marshal(b, m, deterministic)
}
func (m *RegisterRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRespond.Merge(m, src)
}
func (m *RegisterRespond) XXX_Size() int {
	return xxx_messageInfo_RegisterRespond.Size(m)
}
func (m *RegisterRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRespond.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRespond proto.InternalMessageInfo

func (m *RegisterRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterRespond) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRespond) Reset()         { *m = LoginRespond{} }
func (m *LoginRespond) String() string { return proto.CompactTextString(m) }
func (*LoginRespond) ProtoMessage()    {}
func (*LoginRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *LoginRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRespond.Unmarshal(m, b)
}
func (m *LoginRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRespond.Marshal(b, m, deterministic)
}
func (m *LoginRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRespond.Merge(m, src)
}
func (m *LoginRespond) XXX_Size() int {
	return xxx_messageInfo_LoginRespond.Size(m)
}
func (m *LoginRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRespond.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRespond proto.InternalMessageInfo

func (m *LoginRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRespond) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type InfoRespond struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRespond) Reset()         { *m = InfoRespond{} }
func (m *InfoRespond) String() string { return proto.CompactTextString(m) }
func (*InfoRespond) ProtoMessage()    {}
func (*InfoRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *InfoRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRespond.Unmarshal(m, b)
}
func (m *InfoRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRespond.Marshal(b, m, deterministic)
}
func (m *InfoRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRespond.Merge(m, src)
}
func (m *InfoRespond) XXX_Size() int {
	return xxx_messageInfo_InfoRespond.Size(m)
}
func (m *InfoRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRespond.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRespond proto.InternalMessageInfo

func (m *InfoRespond) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InfoRespond) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *InfoRespond) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type CoinAddRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinAddRequest) Reset()         { *m = CoinAddRequest{} }
func (m *CoinAddRequest) String() string { return proto.CompactTextString(m) }
func (*CoinAddRequest) ProtoMessage()    {}
func (*CoinAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *CoinAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinAddRequest.Unmarshal(m, b)
}
func (m *CoinAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinAddRequest.Marshal(b, m, deterministic)
}
func (m *CoinAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinAddRequest.Merge(m, src)
}
func (m *CoinAddRequest) XXX_Size() int {
	return xxx_messageInfo_CoinAddRequest.Size(m)
}
func (m *CoinAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinAddRequest proto.InternalMessageInfo

func (m *CoinAddRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CoinAddRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CoinAddResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinAddResponse) Reset()         { *m = CoinAddResponse{} }
func (m *CoinAddResponse) String() string { return proto.CompactTextString(m) }
func (*CoinAddResponse) ProtoMessage()    {}
func (*CoinAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *CoinAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinAddResponse.Unmarshal(m, b)
}
func (m *CoinAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinAddResponse.Marshal(b, m, deterministic)
}
func (m *CoinAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinAddResponse.Merge(m, src)
}
func (m *CoinAddResponse) XXX_Size() int {
	return xxx_messageInfo_CoinAddResponse.Size(m)
}
func (m *CoinAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoinAddResponse proto.InternalMessageInfo

func (m *CoinAddResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type CoinGetRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinGetRequest) Reset()         { *m = CoinGetRequest{} }
func (m *CoinGetRequest) String() string { return proto.CompactTextString(m) }
func (*CoinGetRequest) ProtoMessage()    {}
func (*CoinGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *CoinGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinGetRequest.Unmarshal(m, b)
}
func (m *CoinGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinGetRequest.Marshal(b, m, deterministic)
}
func (m *CoinGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinGetRequest.Merge(m, src)
}
func (m *CoinGetRequest) XXX_Size() int {
	return xxx_messageInfo_CoinGetRequest.Size(m)
}
func (m *CoinGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinGetRequest proto.InternalMessageInfo

func (m *CoinGetRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CoinGetResponse struct {
	Value                int32    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinGetResponse) Reset()         { *m = CoinGetResponse{} }
func (m *CoinGetResponse) String() string { return proto.CompactTextString(m) }
func (*CoinGetResponse) ProtoMessage()    {}
func (*CoinGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *CoinGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinGetResponse.Unmarshal(m, b)
}
func (m *CoinGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinGetResponse.Marshal(b, m, deterministic)
}
func (m *CoinGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinGetResponse.Merge(m, src)
}
func (m *CoinGetResponse) XXX_Size() int {
	return xxx_messageInfo_CoinGetResponse.Size(m)
}
func (m *CoinGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoinGetResponse proto.InternalMessageInfo

func (m *CoinGetResponse) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "gmicro.srv.user.RegisterRequest")
	proto.RegisterType((*RegisterRespond)(nil), "gmicro.srv.user.RegisterRespond")
	proto.RegisterType((*LoginRequest)(nil), "gmicro.srv.user.LoginRequest")
	proto.RegisterType((*LoginRespond)(nil), "gmicro.srv.user.LoginRespond")
	proto.RegisterType((*InfoRequest)(nil), "gmicro.srv.user.InfoRequest")
	proto.RegisterType((*InfoRespond)(nil), "gmicro.srv.user.InfoRespond")
	proto.RegisterType((*CoinAddRequest)(nil), "gmicro.srv.user.CoinAddRequest")
	proto.RegisterType((*CoinAddResponse)(nil), "gmicro.srv.user.CoinAddResponse")
	proto.RegisterType((*CoinGetRequest)(nil), "gmicro.srv.user.CoinGetRequest")
	proto.RegisterType((*CoinGetResponse)(nil), "gmicro.srv.user.CoinGetResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x5e, 0xd7, 0x56, 0xb7, 0xa7, 0x38, 0x09, 0x1e, 0x4a, 0x51, 0x36, 0x02, 0xe2, 0x4e, 0x3d,
	0xe8, 0xc1, 0x5d, 0xc7, 0xc4, 0x21, 0x88, 0x8e, 0xe2, 0xbc, 0x57, 0x13, 0x4b, 0xd1, 0x35, 0x33,
	0xe9, 0xf4, 0x27, 0xf8, 0xb7, 0x25, 0x49, 0xd3, 0xd5, 0x75, 0xd9, 0xc5, 0xdb, 0x7b, 0xbc, 0xaf,
	0xdf, 0xf7, 0xbd, 0xf7, 0xa5, 0xd0, 0x4d, 0x96, 0x59, 0xb4, 0xe4, 0xac, 0x60, 0xa8, 0x97, 0x2e,
	0xb2, 0x57, 0xce, 0x22, 0xc1, 0xbf, 0xa2, 0x95, 0xa0, 0x1c, 0x33, 0xe8, 0xc5, 0x34, 0xcd, 0x44,
	0x41, 0x79, 0x4c, 0x3f, 0x57, 0x54, 0x14, 0x28, 0x84, 0xce, 0x5c, 0x50, 0x9e, 0x27, 0x0b, 0x1a,
	0x38, 0x03, 0x67, 0xd8, 0x8d, 0xab, 0x5e, 0xce, 0x66, 0x89, 0x10, 0xdf, 0x8c, 0x93, 0xa0, 0xad,
	0x67, 0xa6, 0x47, 0xc7, 0xe0, 0x8e, 0x53, 0x1a, 0xb8, 0x03, 0x67, 0xe8, 0xc7, 0xb2, 0x44, 0x08,
	0xbc, 0x31, 0x21, 0x3c, 0xf0, 0x14, 0x52, 0xd5, 0xf8, 0xba, 0x2e, 0x28, 0x96, 0x2c, 0x27, 0x12,
	0x36, 0x61, 0x44, 0x8b, 0xf9, 0xb1, 0xaa, 0x25, 0xd9, 0x3c, 0x33, 0x1a, 0xb2, 0xc4, 0xb7, 0x70,
	0x78, 0xcf, 0xd2, 0x2c, 0xff, 0xa7, 0x4d, 0x3c, 0xaa, 0x78, 0xec, 0xea, 0x27, 0xe0, 0x3f, 0xb1,
	0x77, 0x9a, 0x97, 0x1f, 0xeb, 0x06, 0xf7, 0xe1, 0xe0, 0x2e, 0x7f, 0x63, 0xc6, 0x40, 0x69, 0xd1,
	0x59, 0x5b, 0x7c, 0x34, 0x00, 0xcd, 0xbc, 0xcb, 0x61, 0x79, 0xac, 0x76, 0xf3, 0x58, 0x6e, 0xed,
	0x58, 0x23, 0x38, 0x9a, 0xb0, 0x2c, 0x1f, 0x13, 0x62, 0x15, 0x95, 0x5e, 0x9f, 0x93, 0x8f, 0x95,
	0xe1, 0xd2, 0x0d, 0x3e, 0x87, 0x5e, 0xf5, 0xa5, 0x74, 0x23, 0xe8, 0xb6, 0x45, 0x31, 0xd6, 0x02,
	0x53, 0x5a, 0xd8, 0xb7, 0xba, 0xd0, 0x54, 0x0a, 0x53, 0x52, 0x55, 0x9a, 0x4e, 0x4d, 0xf3, 0xf2,
	0xc7, 0x05, 0x4f, 0x2e, 0x88, 0x66, 0xd0, 0x31, 0x19, 0xa3, 0x41, 0xb4, 0xf1, 0xe4, 0xa2, 0x8d,
	0xf7, 0x16, 0xee, 0x42, 0xa8, 0x43, 0xe2, 0x16, 0x9a, 0x82, 0xaf, 0x42, 0x43, 0x67, 0x0d, 0x70,
	0xfd, 0x51, 0x84, 0xd6, 0xb1, 0x21, 0xba, 0x01, 0x4f, 0x46, 0x84, 0x4e, 0x1b, 0xc0, 0x5a, 0xb4,
	0xa1, 0x6d, 0x6a, 0x58, 0x1e, 0x60, 0xbf, 0xbc, 0x2e, 0xea, 0x37, 0xa0, 0x7f, 0x13, 0xdb, 0xb2,
	0xde, 0x46, 0x30, 0x6b, 0xbe, 0x29, 0x2d, 0x2c, 0x7c, 0xeb, 0x80, 0x2c, 0x7c, 0xb5, 0x74, 0x70,
	0xeb, 0x65, 0x4f, 0xfd, 0xed, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x9e, 0x2e, 0x9a,
	0xfa, 0x03, 0x00, 0x00,
}
